stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw
    - src/data/data_split.py
    outs:
    - data/processed/split/X_train.csv
    - data/processed/split/X_test.csv
    - data/processed/split/y_train.csv
    - data/processed/split/y_test.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/split/X_train.csv
    - data/processed/split/X_test.csv
    - src/data/normalize.py
    outs:
    - data/processed/scaled/X_train_scaled.csv
    - data/processed/scaled/X_test_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/scaled/X_train_scaled.csv
    - data/processed/split/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/data/best_params.pkl
  training:
    cmd: python src/models/training.py
    deps:
    - data/processed/scaled/X_train_scaled.csv
    - data/processed/split/y_train.csv
    - models/data/best_params.pkl
    - src/models/training.py
    outs:
    - models/models/trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed/scaled/X_test_scaled.csv
    - data/processed/split/y_test.csv
    - models/models/trained_model.pkl
    - src/models/evaluate.py
    outs:
    - data/predicted/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false
